main_project/INTAKE/INTAKE/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main_app.urls', namespace='main_app')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_project/INTAKE/main_app/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "main_app"

urlpatterns = [
    re_path(r'^$', views.main_page, name="main_page"),
    path('product<int:pk>', views.product, name="product"),
    path('category', views.category_main, name="category_main"),
    path('category/<int:pk>', views.category, name="category"),
]

main_project/INTAKE/main_app/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=20, verbose_name='카테고리명',)

    def __str__(self):
        return self.category_name



class Product(models.Model):
    product_name = models.CharField(max_length=20, verbose_name='상품명',)
    category = models.ForeignKey(Category, blank=True, on_delete=models.CASCADE, verbose_name='카테고리')
    product_image = models.ImageField(verbose_name='상품 사진',)
    product_price_before = models.IntegerField(verbose_name='정가',)
    product_price = models.IntegerField(verbose_name='가격',)
    product_register = models.DateTimeField(auto_now_add=True, verbose_name='상품 등록일')
    product_detail = models.TextField(verbose_name='상품 설명')

    # 할인률 계산
    def product_sale(self):
        product_sale = int(100 - 100 * int(self.product_price) / int(self.product_price_before))
        return product_sale

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.product_name


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='작성자')   # Profile의 user와 같은 거?? 따로 부름??
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='해당 상품')

    # star 선택지로
    STATUS_CHOICES2 = (
        (1, '★☆☆☆☆'),
        (2, '★★☆☆☆'),
        (3, '★★★☆☆'),
        (4, '★★★★☆'),
        (5, '★★★★★'),
    )
    star = models.IntegerField(choices=STATUS_CHOICES2, verbose_name='평점')
    content = models.TextField(verbose_name='댓글 내용')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    # comment 쓰고 다시 그 페이지로
    def get_absolute_url(self):
        return reverse('main_app:product', args=[self.product.id])

main_project/INTAKE/main_app/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['star', 'content', ]

main_project/INTAKE/main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CommentForm
from .models import Product, Comment, Category
from django.db.models import Q, Avg


# Create your views here.
def main_page(request):
    # search 구현
    if "search" in request.GET:
        search_term = request.GET["search"]
        if search_term:
            searched_products = Product.objects.filter(
                Q(product_name__icontains=search_term) |
                Q(product_price__icontains=search_term) |
                Q(category__category_name__icontains=search_term)
            ).distinct()
        ctx = {
            'products': searched_products,
            'search_term': search_term,
        }
        return render(request, 'main_app/category.html', ctx)
    else:
        main_products1 = Product.objects.filter(category__pk=1)  # 밀스라이트 제품만 따옴
        main_products2 = Product.objects.filter(category__pk=2)  # 피로그래밍만 따옴
        ctx = {
            'products1': main_products1,
            'products2': main_products2,
        }
        return render(request, 'main_app/main_page.html', ctx)


def product(request, pk):
    # search 구현
    if "search" in request.GET:
        search_term = request.GET["search"]
        if search_term:
            searched_products = Product.objects.filter(
                Q(product_name__icontains=search_term) |
                Q(product_price__icontains=search_term) |
                Q(category__category_name__icontains=search_term)
            ).distinct()
        ctx = {
            'products': searched_products,
            'search_term': search_term,
        }
        return render(request, 'main_app/category.html', ctx)
    else:
        # 상품별 페이지 생성
        product = get_object_or_404(Product, pk=pk)
        # 카테고리 종류 받아오기
        category = product.category
        # 후기 등록 시스템 구현(상품 보여주는 페이지와 같은 곳에서 보이게 구현함)
        form = CommentForm(request.POST, request.FILES or None)
        if request.method == 'POST':
            # 로그인 되었을 때만 쓸 수 있게 할 생각
            if request.user.is_authenticated:
                if form.is_valid():
                    comment = form.save(commit=False)
                    # 자동으로 author와 product 지정
                    comment.author = request.user
                    comment.product = product
                    comment.save()
                    return redirect(comment)        # 다시 상품 해당 페이지로 가야함
                else:
                    form = CommentForm()
            else:
                return redirect('accounts:login')

    # 댓글 목록 받아오기
    comments = Comment.objects.filter(product__pk=pk)

    ctx = {
        'form': form,
        'product': product,
        'category': category,
        'comments': comments,
    }
    return render(request, 'main_app/product.html', ctx)


def category(request, pk):   # 여기서 pk는 category의 pk
    # search 구현
    if "search" in request.GET:
        search_term = request.GET["search"]
        if search_term:
            searched_products = Product.objects.filter(
                Q(product_name__icontains=search_term) |
                Q(product_price__icontains=search_term) |
                Q(category__category_name__icontains=search_term)
            ).distinct()
        ctx = {
            'products': searched_products,
            'search_term': search_term,
        }
        return render(request, 'main_app/category.html', ctx)
    else:
        # 해당 카테고리의 상품 받아오기
        products = Product.objects.filter(category__pk=pk)
        # 해당 카테고리 받아오기
        category = products[0].category

        # sort 구현
        sort_option = "최신 상품순"
        if "sort" in request.GET:
            sort_option = request.GET["sort"]
            if sort_option == "최신 상품순":
                sorted_products = products
            elif sort_option == "댓글 수":
                sorted_products = sorted(products, key=lambda x: x.comment_set.count(), reverse=True)
            elif sort_option == "상품평순":
                sorted_products = sorted(products,
                                         key=lambda x: x.comment_set.all().aggregate(Avg('star'))['star__avg'],
                                         reverse=True)                # aggregate로 필드 내 요소들에 접근 가능!
            elif sort_option == "낮은 가격순":
                sorted_products = sorted(products, key=lambda x: x.product_price)
            elif sort_option == "높은 가격순":
                sorted_products = sorted(products, key=lambda x: x.product_price, reverse=True)
            # else:
            #     sorted_products = Product.objects.filter(category__pk=pk)
            ctx = {
                'products': sorted_products,
                'sort_option': sort_option,
                'category': category,
            }
            return render(request, 'main_app/category.html', ctx)
        else:
            ctx = {
                'products': products,
                'sort_option': sort_option,
                'category': category,
            }
            return render(request, 'main_app/category.html', ctx)


def category_main(request):
    # 카테고리 목록 받아오기
    categorys = Category.objects.all()
    ctx = {
        'categorys': categorys,
    }
    return render(request, 'main_app/category_main.html', ctx)

main_project/INTAKE/main_app/templates/main_app/category.html
{% extends "base.html" %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'main_app/css/category.css' %}">

  <!--relation_var-->
  {% if category %}
  <div class="relation_bar">
    <div>
      <span><a href="{% url "main_app:main_page" %}">Home</a></span>
      <span>  >  </span>
      <span><a href="{% url "main_app:category_main" %}">Category</a></span>
      <span>  >  </span>
      <span><a href="#">{{ category }}</a></span>
    </div>
  </div>
  {% endif %}

  <!--category-title-->
  <div class="category_title">
    {% if category %}
      <div><b>{{ category }}</b></div>
      <div>
{#        <form action="" method="GET">#}
{#          <input name="sort" list="order" placeholder="{{ sort_option }}">#}
{#            <datalist id="order">#}
{#            <option value="최신 상품순">#}
{#            <option value="댓글 수">#}
{#            <option value="상품평순">#}
{#            <option value="낮은 가격순">#}
{#            <option value="높은 가격순">#}
{#            </datalist>#}
{#        </form>        #}
        <form action="" method="GET">
          <select name="sort" id="option" onchange="this.form.submit()">
            <option value="최신 상품순">최신 상품순</option>
            <option value="댓글 수">댓글 수</option>
            <option value="상품평순">상품평순</option>
            <option value="낮은 가격순">낮은 가격순</option>
            <option value="높은 가격순">높은 가격순</option>
          </select>
          <noscript><input type="submit" value="Submit"></noscript>
        </form>
      </div>
    {% else %}
      <div style="margin-top: 50px"><b style="color: orange">"{{ search_term }}"</b>의 검색 결과</div><div></div>
    {% endif %}
  </div>

    <div class="products">
      {% for product in products %}
        <a href="{% url "main_app:product" pk=product.pk %}">
          <div class="product">
            <div>
              <img src="{{ product.product_image.url }}">
            </div>
            <div>
              <div class="product_detail_contents">
              <p>{{ product.product_name }}</p>
              <span class="x">{{ product.product_price_before }}원</span><span>{{ product.product_price }}원</span>
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>


{% endblock %}

main_project/INTAKE/main_app/templates/main_app/category_main.html
{% extends "base.html" %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'main_app/css/category_main.css' %}">

  <!--relation_var-->
  <div class="relation_bar">
    <div>
      <span><a href="{% url "main_app:main_page" %}">Home</a></span>
      <span>  >  </span>
      <span><a href="#">Category</a></span>
    </div>
  </div>

  <!--title-->
  <div class="title">
    <div><b>Category</b></div>
  </div>

  <div class="categorys">
    {% for category in categorys %}
      <a href="{% url "main_app:category" pk=category.pk %}">
        <div class="category">
          <div class="category_title">{{ category }}</div>
        </div>
      </a>
    {% endfor %}
  </div>


{% endblock %}

main_project/INTAKE/main_app/templates/main_app/main_page.html
{% extends "base.html" %}

{% block content %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'main_app/css/main_page.css' %}">

   <!-- section -->
  <div class="section">
     <!-- sectoon1 -->
    <div class="main_image">
      <ul class="slider" id="main_slide">
        <li><img src="{% static 'images/main01.jpg' %}" width="100%"></li>
        <li><img src="{% static 'images/main02.jpg' %}" width="100%"></li>
        <li><img src="{% static 'images/main03.jpg' %}" width="100%"></li>
      </ul>
    </div>
    <div class="product_introduction1">
      <div class="helper"></div> <div>
      <div>Do not eat, Do intake!</div>
      <div>식사를 연구하다, 인테이크</div>
      <div>인테이크는 현대인의 식사를 연구하고 솔루션을 제안합니다.</div>
      </div>
    </div>

    <!--그냥 이미지만 따온 부분-->
    <img class="help_img" src="{% static 'main_app/images/product_help_image.jpg' %}">

    <div class="product_introduction2">
      <div><span>INTAKE</span><span> </span><span style="font-weight: bold">MEAL</span></div>
      <div class="products">
        <div class="subslider">
          {% for product in products1 %}
             <a href="{% url "main_app:product" pk=product.pk %}">
              <div class="product">
                <div>
                  <img src="{{ product.product_image.url }}">
                </div>
                <div>
                  <div class="product_detail_contents">
                  <p>{{ product.product_name }}</p>
                  <span class="x">{{ product.product_price_before }}원</span><span>{{ product.product_price }}원</span>
                  </div>
                </div>
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>

    <div class="product_introduction2">
      <div><span>P.</span><span> </span><span style="font-weight: bold">ROGRAMING</span></div>
      <div class="products">
        <div class="subslider">
          {% for product in products2 %}
             <a href="{% url "main_app:product" pk=product.pk %}">
              <div class="product">
                <div>
                  <img src="{{ product.product_image.url }}">
                </div>
                <div>
                  <div class="product_detail_contents">
                  <p>{{ product.product_name }}</p>
                  <span class="x">{{ product.product_price_before }}원</span><span>{{ product.product_price }}원</span>
                  </div>
                </div>
              </div>
            </a>
          {% endfor %}
        </div>
      </div>
    </div>

    <div class="event"></div>

     <!-- sectoon2 -->
    <div class="movie">

    </div>

       <!-- notice -->

  </div>

     <!-- quickbar -->
    <div class="quickbar">
      <a href="#" class="quickbar_menu"><img src="{% static 'images/quick01.jpg' %}"></a>
      <a href="#" class="quickbar_menu"><img src="{% static 'images/quick02.png' %}"></a>
      <a href="#" class="quickbar_text"></a>
      <a href="#" class="quickbar_menu"><img src="{% static 'images/quick03.jpg' %}"></a>
      <a href="#" class="quickbar_menu"><img src="{% static 'images/quick04.png' %}"></a>
    </div>

{% endblock %}

main_project/INTAKE/main_app/templates/main_app/product.html
{% extends "base.html" %}

{% block content %}
  {% load mathfilters %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'main_app/css/product.css' %}">

  <!--relation_var-->
  <div class="relation_bar">
    <div>
      <span><a href="{% url "main_app:main_page" %}">Home</a></span>
      <span>  >  </span>
      <span><a href="{% url "main_app:category_main" %}">Category</a></span>
      <span>  >  </span>
      <span><a href="{% url "main_app:category" pk=category.pk %}">{{ category }}</a></span>
    </div>
  </div>

  <!--product-->
  <div class="product">
    <div class="product_img">
      <span class="big_img">
        <img src="{{ product.product_image.url }}" width="300px" />
      </span>
      <span class="small_img">
        <img src="{{ product.product_image.url }}" width="80px" />
      </span>
    </div>

    <div class="product_txt">
      <div>인테이크</div>
      <div>{{ product.product_name }}</div>

      <table>
        <tr><td>정가</td><td>{{ product.product_price_before }}원</td></tr>
        <tr><td>인테이크 판매가</td><td><span>{{ product.product_price }}원</span><span>{{ product.product_sale }}% 할인</span></td></tr>
        <tr><td>배송구분</td><td>배송비 2,500원<30,000원 이상 구매시 무료배송></td></tr>
        <tr><td>옵션선택</td><td>input 넣자</td></tr>
        <tr><td>000</td><td>개수 계산 하는거</td></tr>
        <tr><td>총금액</td><td>00000</td></tr>
      </table>
        <div class="when">배송 예정일: 00000</div>

      <div class="select_bar">
        <span><a><img src="{% static 'main_app/images/buy_btn.jpg' %}" width="150"></a></span>
        <span><a><img src="{% static 'main_app/images/cart_btn.jpg' %}" width="150"></a></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>


  <!--product_detail-->
  <div class="product_detail">
    <div><img src="{% static 'main_app/images/introduction.jpg' %}"></div>
  </div>

  <!--comments-->
  <div class="comments">
    <div>총 <span>{{ comments.count }}개</span>의 후기가 있습니다.</div>
    <table>
      {% for comment in comments %}
        <tr>
          {% with forloop.counter as commnet_number %}
            <td>{{ comments.count|add:1|sub:commnet_number }}</td>
          {% endwith %}
          <td>
            <div>{{ comment.content }}</div>
            <div><span>{{ comment.author }}</span><span>{{ comment.created_at | date:"y.m.d" }}</span></div>
          </td>
          <td>
            {% with comment.star as n %}
            {% for i in ''|center:n %}
              <span>★</span>
            {% endfor %}
              {% with 5|sub:n as spare %}
                {% for i in ''|center:spare %}
                  <span>☆</span>
                {% endfor %}
              {% endwith %}
            {% endwith %}
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>

  <!--make_comment-->
  <div class="make_comment">
    <form action="" method="POST">
      {% csrf_token %}
      <div class="post_title"><i>COMMENT</i></div>
      <div class="star"><span>별점</span><span>{{ form.star }}</span></div>
      <div class="content"><span>내용</span><span>{{ form.content }}</span></div>
      <div class="center"><input class="posting" type="submit"/></div>
    </form>
  </div>



  <!--q&a-->
  <div class="q&a"></div>


{% endblock %}