intake/intake/intake/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='notice:post_list')),
    url(r'^admin/', admin.site.urls),
    url(r'^notice/', include('notice.urls')),
]

intake/intake/notice/urls.py
from django.urls import path
from .import views

app_name = "notice"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('/<int:pk>', views.post_detail, name='post_detail'),
]


intake/intake/notice/models.py
from django.db import models

# Create your models here.


class Post(models.Model):

    title = models.CharField(max_length=100, verbose_name='제목')
    content= models.TextField()

    updated_at=models.DateTimeField(auto_now=True, verbose_name='날짜')

    class Meta:
        ordering=['-id']

    def __str__(self):
        return self.title

intake/intake/notice/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.


def post_list(request):
    qs = Post.objects.all()

    return render(request, 'notice/post_list.html', {
        'post_list': qs,
    })


def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'notice/post_detail.html', {
        'post': post,
    })


intake/intake/notice/templates/notice/post_detail.html
<!DOCTYPE html>
<html lang="en" xmlns:notice="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="UTF-8">
  <title>{{ post.title }}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static "notice/post_detail.css" %}" />
</head>



<body>




      <table class="table table-hover table-bordered">
        <thead>
          <div class="divhead">
            <tr class="notice_head">
              <th class="num">#</th>
              <th class="title">제목</th>
              <th class="date">날짜</th>
            </tr>
          </div>
        </thead>

        <tbody>
        <tr>
          <td>{{post.pk}}</td>



        </tr>
        </tbody>

      </table>


      {{post.pk}}<a><h1>{{ post.title }}</h1></a>

      {{ post.content|linebreaks }}


    </div>
  </div>
</div>





{{ post.content|linebreaks }}

<a href="{% url "notice:post_list" %}" class="btn btn-primary">목록으로</a>


</body>
</html>

intake/intake/notice/templates/notice/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  {% load static %}
  <link rel="stylesheet" href="{% static "notice/post_list.css" %}" />

</head>
<body>
<h3>공지사항</h3>

<div class="notice_tab">
  <ul>
    <li class="on">
      <a href="#">공지사항</a>
    </li>
    <li class="on">
      <a href="#">FAQ</a>
    </li>
    <li class="on">
      <a href="#">1:1문의</a>
    </li>
  </ul>
</div>

<ul>
<table class="table table-hover table-bordered">
  <thead>
    <div class="divhead">
      <tr class="notice_head">
        <th class="num">#</th>
        <th class="title">제목</th>
        <th class="date">날짜</th>

      </tr>
    </div>
  </thead>
    <tbody>
      {% for post in post_list %}
      <tr>
        <td class="textid">{{post.id}}</td>

        <div class="we">
          <td class="texttitle"><a href="{% url "notice:post_detail" pk=post.pk %}">
          {{post.title}}
          </a></td>
        </div>


        <td>{{post.updated_at}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</ul>


</body>
</html>