main_project/INTAKE/INTAKE/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main_app.urls', namespace='main_app')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_project/INTAKE/accounts/urls.py
from django.urls import path, re_path, include
from . import views
from django.conf import settings

app_name = "accounts"

urlpatterns = [
    # path('profile/', views.profile, name="profile"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name="login"),
    path('logout/', views.view_logout, name="logout"),
    path('profile/', views.profile, name='profile'),
]

main_project/INTAKE/main_app/urls.py
from django.urls import path, re_path, include
from . import views

app_name = "main_app"

urlpatterns = [
    re_path(r'^$', views.main_page, name="main_page"),
    path('product<int:pk>', views.product, name="product"),
    path('category', views.category_main, name="category_main"),
    path('category/<int:pk>', views.category, name="category"),
]

main_project/INTAKE/INTAKE/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>INTAKE | 인테이크</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

{#이하로 삽입한 css, script#}

  <link rel="stylesheet" href="{% static 'images/jquery.bxslider.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

   <script>
    $(document).ready(function(){
      $('.slider').bxSlider({
        auto: true,
        speed: 500,
        pause: 2000,
        mode:'horizontal',
        infiniteLoop: true,
        autoHover: true,
        minSlides: 1,
        maxSlides: 1,
        pager: true,
        controls: true,
     });

    $('.subslider').bxSlider({
        slideWidth: 318,
        slideMargin: 2,
        auto: true,
        speed: 500,
        pause: 2000,
        mode:'horizontal',
        infiniteLoop: true,
        autoHover: true,
        minSlides: 4,
        maxSlides: 4,
        moveSlides: 3,
        pager: false,
        controls: true,
        nexttext: '>',
        prevText: '<',
        nextSelector: '#slider-next',
        prevSelector: '#slider-prev',
      });
        // controls=true가 좌우 버튼값이 보이게 하는게 맞는데
        // 이유는 모르겠고 그냥 안댐.ㅠㅠㅠㅠ 만약 된다면 nexttext prevtext로 적용할수 있는건지도 모르겠음잘....

    $('#mainslide').bxSlider({
      nextSelector: '#slider-next',
      prevSelector: '#slider-prev',
      nextText: '<img src="iimages/lightarrow.png" %}" />',
      prevText: '<img src="iimages/leftarrow.png" %}" />'    });
   $(function() {
   $(window).scroll(function() {
   var top = $(window).scrollTop();
   $(".quickbar").animate({"top" : top + 100 + "px"}, 100);
  });
  $(".quickbar").click(function() { $("html,body").animate({scrollTop:0}, 10); });
 });
 });

</script>
</head>
<body>
  <!-- 위 3줄 + nav_bar -->
  <div class="head">
    <div class="login_bar">
      <ul>
        {% if not user.is_authenticated %}
          <li><a href="{% url "accounts:login" %}">Login</a></li>
{#          <li><a href="{% url "accounts:login" %}?next={{ request.path }}">Login</a></li>#}
          <li><a href="{% url "accounts:signup" %}">Join</a></li>
        {% else %}
          <li>
            <form class="logout_link" action="{% url "accounts:logout" %}" method="POST">
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
          </li>
{#          <li>#}
{#            <a href="{% url "accounts:logout" %}">Logout</a>#}
{#          </li>#}
          <li><a href="{% url "accounts:profile" %}">MYPAGE</a></li>
        {% endif %}
        <li><a href="#">Cart</a></li>
        <li><a href="#">Customer Center</a></li>
      </ul>
    </div>

    <div class="menu_bar">
      <ul>
        <li>About INTAKE</li>
        <li>Magazine</li>
        <li>Lab</li>
        <li>Best</li>
      </ul>

      <a href="{% url "main_app:main_page" %}">
        <div class="menu_bar_logo"><div class="helper"></div><img src="{% static 'images/logo.png' %}" width="80"></div>
      </a>

      <!--검색창-->
      <div class="search">
        <div>
          <form action="" method="GET">        <!--get으로 받을 예정-->
            <input class="search_content" type="search" name="search"
                   placeholder="검색어를 입력하세요." value="{{ request.GET.search }}">
            <input class="search_btn" type="submit" value="SEARCH">
          </form>
        </div>

      </div>
    </div>

    <nav>
      <div class="product_bar">
        <ul class="product_category">
          <li><img src="{% static 'images/menu.png' %}" height="100%"></li>
          <li><a href ="#" class="product_menu">밀스</a></li>
            <ul class="submenu">
              <li> <a href="#" class="product_submenu" id="submenu_first"><img src="{% static 'images/subimage01.jpg' %}" class="submenu_image"><p class="submenu_exp">밀스드링크</p></a></li>
              <li> <a href="#" class="product_submenu"><img src="{% static 'images/subimage02.jpg' %}" class="submenu_image"><p class="submenu_exp">밀스드링크</p></a></li>
              <li> <a href="#" class="product_submenu"><img src="{% static 'images/subimage03.jpg' %}" class="submenu_image"><p class="submenu_exp">밀스드링크</p></a></li>
              <li> <a href="#" class="product_submenu"><img src="{% static 'images/subimage04.jpg' %}" class="submenu_image"><p class="submenu_exp">밀스드링크</p></a></li>
            </ul>
          <li><a href ="#" class="product_menu">아침간편식</a></li>
          <li><a href ="#" class="product_menu">한끼</a></li>
          <li><a href ="#" class="product_menu">간식/음료</a></li>
          <li><a href ="#" class="product_menu">서플리먼트</a></li>
          <li><a href ="#" class="product_menu">다이어트/스포츠</a></li>
          <li><a href ="#" class="product_menu">이벤트</a></li>
        </ul>
      </div>
    </nav>

    <div class="nav_bar"></div>
  </div>

  <div>
    {% block content %}
    {% endblock %}
  </div>

   <!-- footer -->
  <div class="footer_bar">
    <img src="{% static 'images/footer.jpg' %}" style="width: 100%;">
  </div>
  <div class="company_introduction"></div>

</body>
</html>

main_project/INTAKE/INTAKE/templates/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>INTAKE | 인테이크</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base_app.css' %}">
</head>
<body>
  <!-- 위 3줄 + nav_bar -->
  <div class="head">
    <div class="login_bar">
      <ul>
        {% if not user.is_authenticated %}
          <li><a href="{% url "accounts:login" %}">Login</a></li>
{#          <li><a href="{% url "accounts:login" %}?next={{ request.path }}">Login</a></li>#}
          <li><a href="{% url "accounts:signup" %}">Join</a></li>
        {% else %}
          <li>
            <form class="logout_link" action="{% url "accounts:logout" %}" method="POST">
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
          </li>
{#          <li>#}
{#            <a href="{% url "accounts:logout" %}">Logout</a>#}
{#          </li>#}
          <li><a href="{% url "accounts:profile" %}">MYPAGE</a></li>
        {% endif %}
        <li><a href="#">Cart</a></li>
        <li><a href="#">Customer Center</a></li>
      </ul>
    </div>

    <div class="menu_bar">
      <ul>
        <li>About INTAKE</li>
        <li>Magazine</li>
        <li>Lab</li>
        <li>Best</li>
      </ul>

      <a href="{% url "main_app:main_page" %}">
        <div class="menu_bar_logo"><div class="helper"></div><img src="{% static 'images/logo.png' %}" width="80"></div>
      </a>

      <!--검색창-->
      <div class="search">
        <div>
          <form action="" method="GET">        <!--get으로 받을 예정-->
            <input class="search_content" type="search" name="search"
                   placeholder="검색어를 입력하세요." value="{{ request.GET.search }}">
            <input class="search_btn" type="submit" value="SEARCH">
          </form>
        </div>

      </div>
    </div>

    <div class="product_bar">
      <div class="product_category"></div>
    </div>

    <div class="nav_bar"></div>
  </div>

  <div>
    {% block content %}
    {% endblock %}
  </div>

   <!-- footer -->
  <div class="footer_bar">
    <img src="{% static 'images/footer.jpg' %}" style="width: 100%;">
  </div>
  <div class="company_introduction"></div>

</body>
</html>